---
- hosts: mariadb
  connection: local
  tasks:

  - name: Create DB's on DB servers
    community.mysql.mysql_db:
      login_user: "{{ db_user }}"
      login_password: "{{ db_password }}"
      login_host: "{{ ansible_host }}"
      name: "{{ db_list }}"
      state: present

  - name: Delete DB's on DB servers
    community.mysql.mysql_db:
      login_user: "{{ db_user }}"
      login_password: "{{ db_password }}"
      login_host: "{{ ansible_host }}"
      name: "{{ db_list }}"
      state: present    